import Link from "next/link";
import "../globals.css";
import { Livvic } from "next/font/google";

const livvic = Livvic({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "MY Awesome Site",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={livvic.className}>
      <body className="max-w-5xl mx-auto py-10" >
        <header>
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Back to Home
          </Link>
        </header>

        <main className="py-20">
          {children}
        </main>
      </body>
    </html>
  );
}
